permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author: 
  name: 如来神掌
  email: quanlongwang@gmail.com
  link: http://lnmp100.com
  github: http://github.com/qloog

# 站点信息
title: LNMP100实验室 
description: LNMP100实验室
url: http://lnmp100.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
# ga:
#   id: UA-54767140-1
#   url: yansu.org

# disqus 设置
disqus:
  shortname: lnmp100


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
# filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
github:   qloog
# codepen:  username
# dribbble: username