# Site settings
title: LNMP100实验室
# email: your-email@domain.com
description: LNMP100实验室
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lnmp100.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
github:   qloog
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: lnmp100


# Google Analytics
# google_analytics: tracking_ID


# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
gems:
  - jekyll-sitemap

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico  
