title: LNMP100 
name: LNMP100
email: quanlongwang@gmail.com
description: LNMP100 GitHub:https://github.com/qloog。
keywords: Laravel
skill_keywords: [
    PHP, MySQL, Linux, Redis, Memcache, Laravel,
    C, C扩展, Go, Docker
    JavaScript, HTML+CSS, 
    Mac, Git, VIM, PHPStorm, Composer, 
    RESTful, Stackoverflow 
]

timezone:    PRC
encoding: "utf-8"

url: http://lnmp100.com
baseurl:  "/"
domain:    lnmp100.com
permalink:     /:year/:month/:day/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/qloog/qloog.github.io

# Build settings
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  # # # - jekyll-mentions
  # - jekyll-sitemap
  - jekyll-html-pipeline

disqus:
  id: lnmp100

google:
    analytics_id: UA-27269744-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: https://github.com/qloog
    label: GitHub
    target: _blank

  -
    href: /bookmark
    label: Bookmark

  -
    href: /manual
    label: Manual

  -
    href: /about
    label: About

popular_repos: ['laravel5-backend']
#contribute_repos: ['laravel/framework', 'tymondesigns/jwt-auth', 'caouecs/Laravel-lang']
resource_recommend: [
    {'name': '博客推荐','url':'2015/07/16/blog-collection.html'}
]
